version: "3.9"

services:
  app:
    image: elestio/papermerge:${SOFTWARE_VERSION_TAG}
    environment:
      - PAPERMERGE__MAIN__SECRET_KEY=${PAPERMERGE__SECURITY__SECRET_KEY}
      - DJANGO_SUPERUSER_PASSWORD=${PAPERMERGE__AUTH__PASSWORD}
      - PAPERMERGE__DATABASE__TYPE=postgres
      - PAPERMERGE__DATABASE__USER=${POSTGRES_USER}
      - PAPERMERGE__DATABASE__PASSWORD=${POSTGRES_PASSWORD}
      - PAPERMERGE__DATABASE__NAME=${POSTGRES_DB}
      - PAPERMERGE__DATABASE__HOST=db
    ports:
      - 172.17.0.1:12000:8000
    depends_on:
      - db
  db:
    restart: always
    image: elestio/postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 172.17.0.1:56225:5432
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:8575:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
